/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'IIc:baselinePause': typeof import('~icons/ic/baseline-pause')['default']
    'IIc:baselinePlayArrow': typeof import('~icons/ic/baseline-play-arrow')['default']
    'IIc:outlineRepeat': typeof import('~icons/ic/outline-repeat')['default']
    'IIc:outlineRepeatOne': typeof import('~icons/ic/outline-repeat-one')['default']
    'IIc:outlineShuffle': typeof import('~icons/ic/outline-shuffle')['default']
    'IIc:roundSkipNext': typeof import('~icons/ic/round-skip-next')['default']
    'IIc:roundSkipPrevious': typeof import('~icons/ic/round-skip-previous')['default']
    'IMage:next': typeof import('~icons/mage/next')['default']
    'IMage:previous': typeof import('~icons/mage/previous')['default']
    'IMaterialSymbolsLight:pauseCircleOutlineRounded': typeof import('~icons/material-symbols-light/pause-circle-outline-rounded')['default']
    'IMaterialSymbolsLight:playCircleOutlineRounded': typeof import('~icons/material-symbols-light/play-circle-outline-rounded')['default']
    'IRi:arrowDownSLine': typeof import('~icons/ri/arrow-down-s-line')['default']
    'IRi:arrowUpSLine': typeof import('~icons/ri/arrow-up-s-line')['default']
    'IRi:playList2Line': typeof import('~icons/ri/play-list2-line')['default']
    'IRi:volumeUpLine': typeof import('~icons/ri/volume-up-line')['default']
  }
}
